import { mountSuspended } from '@nuxt/test-utils/runtime'
import { describe, it, expect } from 'vitest'
import RaceRoundResultsList from '@/components/RaceRoundResultsList/RaceRoundResultsList.vue'
import { mockRaceRounds } from '../helpers/mockData'

describe('Race Round Results List', () => {
  it('should render data generated by store actions', async () => {
    const mockRounds = mockRaceRounds()

    const component = await mountSuspended(RaceRoundResultsList, {
      props: {
        rounds: mockRounds
      }
    })

    // 6 rounds, each round a table for its results
    expect(component.findAll('.el-table')).toHaveLength(6)

    // 6 tables, each table 10 rows = 60
    expect(component.findAll('.el-table__row')).toHaveLength(60)

    // check table title
    expect(component.text()).toContain('Round 1')

    // clear first round results, so its table should show No Data
    mockRounds[0]!.results = []
    component.setProps({ rounds: mockRounds })
    await nextTick()
    expect(component.html().match(/No Data/g)).toHaveLength(1)
  })
})
