import { mountSuspended } from '@nuxt/test-utils/runtime'
import { describe, it, expect } from 'vitest'
import RaceProgramsList from '@/components/RaceProgramsList/RaceProgramsList.vue'
import { useAppStore } from '@/stores/app'

describe('Race Programs List', () => {
  it('should render data generated by store actions', async () => {
    const store = useAppStore()
    const component = await mountSuspended(RaceProgramsList)

    store.addNewRaceProgram()
    await nextTick()
    expect(component.findAll('.el-collapse-item')).toHaveLength(1)
    store.addNewRaceProgram()
    await nextTick()
    expect(component.findAll('.el-collapse-item')).toHaveLength(2)
    store.addNewRaceProgram()
    store.addNewRaceProgram()
    store.addNewRaceProgram()
    await nextTick()
    expect(component.findAll('.el-collapse-item')).toHaveLength(5)

    expect(component.text()).toContain('Program 1')
    expect(component.text()).toContain('Program 5')
  })
})
